### ISSUE TITLE
UART_PM_Sensor does not return HPM115S0 values

### ISSUE THREAD

**Issue by chrpaq** [ElektorLabs/191148-RemakeWeatherStation#19]
The GetParticleCount does not return the counts comming from HPM115S0 sensor.
float values p25 and p10 are assigned the count from SDS011 but when reading values from HPM115S0 are assigned to integer variables up25 and up10. 
I have added following code after line: reading_ok=HPMA115S0device->ReadMesurement(&up25, &up10);
                   if (reading_ok){
		      p25 = up25;
		      p10 = up10;
		   }
With this correction I now have the values back from the HPM sensor.

**Comment by lab-mathias-claussen** [comment]
Fixed by Pullrequest #18
