### ISSUE TITLE
Raindrop & WindSpeed

### ISSUE THREAD

**Issue by Kal-lan** [ElektorLabs/191148-RemakeWeatherStation#22]
Hello everyone

I use USERBTN1 as an input where a rain sensor is connected.
O = sensor wet 1 = sensor dry.

When the sensor is wet, the command to close is sent to a shelly.

Where and how can the wind speed data be processed?

int Veriegelung = 0;
void loop() {
  /* This will be executed in the arduino main loop */
 
  ArduinoOTA.handle();
  NetworkLoopTask();
   byte tasterstatus = digitalRead(USERBTN1);
   if (tasterstatus == LOW && Veriegelung == 0){
   NetworkDropTask();
   Veriegelung = 1;   
   }
   if (tasterstatus == HIGH && Veriegelung == 1){
   Veriegelung = 0 ;
   }
#include <Arduino.h>
#include <WiFi.h>
#include <HTTPClient.h>
#include "datastore.h"
//Your Domain name with URL path or IP address with path
const char* serverName = "http://192.168.178.63/roller/0?";
unsigned long lastTime = 0;
unsigned long timerDelay = 5000;

void NetworkDropTask(){
  //Send an HTTP POST request every 10 minutes
  if ((millis() - lastTime) > timerDelay) {
    //Check WiFi connection status
    if(WiFi.status()== WL_CONNECTED){
      HTTPClient http;
      
      http.begin(serverName);

      String httpRequestData = "go=close";           
      // Send HTTP POST request
      int httpResponseCode = http.POST(httpRequestData);
      
      //Responsecode   200 = OK
      //Responsecode   400 = Bad Request
      //https://de.wikipedia.org/wiki/HTTP-Statuscode     
      Serial.print("HTTP Response code: ");
      Serial.println(httpResponseCode);
        
      // Free resources
      http.end();
    }
    else {
      Serial.println("WiFi Disconnected");
    }
    lastTime = millis();
  }
}

**Comment by lab-mathias-claussen** [comment]
Hi Kal-lan,

the data is processed a bit different than what you did. Every sensor or input will be transofmed into a sensor device and mapped to a virtual channel. have a lookk into the driver structure. What you want to do is a modified connector as they are called. You need to do a basic io driver connect it to the mapper and read later the mapped value through a connector.

Best Regards

Mathias Claußen
