### ISSUE TITLE
VEML6070 detected but not enumerated

### ISSUE THREAD

**Issue by ginodecock** [ElektorLabs/191148-RemakeWeatherStation#3]
Hi,

I have connected only an VEML6070 sensor.

**Startup:**
VEML6070 found @ 0x38
lcdmenu
Initialize WiFi
Starting Reconnect
Connection Task
Station Mode Started
WiFi interface ready
.Connected to access point

The sensor is found but cannot be assigned to any sensor channel:

![image](https://user-images.githubusercontent.com/6877889/86533463-c58cc200-bed1-11ea-903d-870a02225175.png)

**Comment by ginodecock** [comment]
I found the BUG:
in i2c_sensers.cpp

   if(true ==  uv_6075.begin() ){
        Serial.println("VEML6075 found @ 0x10");
        DeviceOnBus[VEML6075] = true;
    } else {
        #ifdef DEBUG_SERIAL
            Serial.println("No VEML6075 found");
        #endif
        DeviceOnBus[VEML6070] = false; **//This should be ==> DeviceOnBus[VEML6075] = false;**
    }

**Comment by lab-mathias-claussen** [comment]
Hi ginodecock,

thanks for the bug submission and also the debugging. We will correct the code and put a new version on github.

Best Regards 

ElektorLabs
