### ISSUE TITLE
SDS011 sensor detected but not uploading

### ISSUE THREAD

**Issue by ginodecock** [ElektorLabs/191148-RemakeWeatherStation#5]
### When connecting an SDS011 particle sensor. 

**It is detected:**
_VEML6070 found @ 0x38
Starting auto detect
Configure SDS011: Query Mode
Initialize WiFi
Starting Reconnect
Connection Task
Station Mode Started
WiFi interface ready_

**It is configured:**
![sds011-1](https://user-images.githubusercontent.com/6877889/87241441-5c520500-c423-11ea-982c-44e5d7d0daff.GIF)
![sds011-2](https://user-images.githubusercontent.com/6877889/87241442-5e1bc880-c423-11ea-8de5-273ec81c7962.GIF)

**But it is not reporting to thingspeak:**
https://thingspeak.com/channels/1094431

**Comment by lab-mathias-claussen** [comment]
Hi ginodecock,

we need to look into it where the values get stuck, or if the post for Thingspeak may is not as it should. As with the WiFi we try to recreate this missfunction but it will need some momemts to assamble the setup. 

Best Regards
ElektorLabs

**Comment by ginodecock** [comment]
Hi Mathias,

I've also connected an TLS2561 sensor. It was detected but just like the SDS011 particle sensor, readings are not posted to Thingspeak.

**Comment by ginodecock** [comment]
It seems that the Thingspeak field are not populated with values:

VEML6070 found @ 0x38
TSL2561 found @ 0x39
Starting auto detect
Configure SDS011: Query Mode
Filesize:249{"Mapping":[{"Enabled":true,"Channel":6},{"Enabled":true,"Channel":7},{"Enabled":true,"Channel":8},{"Enabled":true,"Channel":9},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0}]}
JSON:{"Mapping":[{"Enabled":true,"Channel":6},{"Enabled":true,"Channel":7},{"Enabled":true,"Channel":8},{"Enabled":true,"Channel":9},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0}]}
Read form File for Thingspeak Channel0
Mapped to Station Channel:6
Channel is Enabled
Read form File for Thingspeak Channel1
Mapped to Station Channel:7
Channel is Enabled
Read form File for Thingspeak Channel2
Mapped to Station Channel:8
Channel is Enabled
Read form File for Thingspeak Channel3
Mapped to Station Channel:9
Channel is Enabled
Read form File for Thingspeak Channel4
Mapped to Station Channel:0
Channel is Disabled
Read form File for Thingspeak Channel5
Mapped to Station Channel:0
Channel is Disabled
Read form File for Thingspeak Channel6
Mapped to Station Channel:0
Channel is Disabled
Read form File for Thingspeak Channel7
Mapped to Station Channel:0
Channel is Disabled
Initialize WiFi
Starting Reconnect
Connection Task
Station Mode Started
WiFi interface ready
.Connected to access point
Connected to :XXXXXXXX
Got IP: 192.168.168.45
Checking connected Callbacks
Execute Connected Callback
Start OTA Service
Execute Connected Callback
Execute Connected Callback
Start UPD Server Task
Filesize:249{"Mapping":[{"Enabled":true,"Channel":6},{"Enabled":true,"Channel":7},{"Enabled":true,"Channel":8},{"Enabled":true,"Channel":9},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0}]}
JSON:{"Mapping":[{"Enabled":true,"Channel":6},{"Enabled":true,"Channel":7},{"Enabled":true,"Channel":8},{"Enabled":true,"Channel":9},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0},{"Enabled":false,"Channel":0}]}
Read form File for Thingspeak Channel0
Mapped to Station Channel:6
Channel is Enabled
Read form File for Thingspeak Channel1
Mapped to Station Channel:7
Channel is Enabled
Read form File for Thingspeak Channel2
Mapped to Station Channel:8
Channel is Enabled
Read form File for Thingspeak Channel3
Mapped to Station Channel:9
Channel is Enabled
Read form File for Thingspeak Channel4
Mapped to Station Channel:0
Channel is Disabled
Read form File for Thingspeak Channel5
Mapped to Station Channel:0
Channel is Disabled
Read form File for Thingspeak Channel6
Mapped to Station Channel:0
Channel is Disabled
Read form File for Thingspeak Channel7
Mapped to Station Channel:0
Channel is Disabled
Thinkspeak UploadTask started
Thingspeak will upload in 60000 Ticks( ms )
Thingspeak: Config changed, apply settings
Thingspeak will upload in 60000 Ticks( ms )
Execute Connected Callback
Webserver started at port 80

WiFi connected!
IP address: 192.168.168.45
ESP Mac Address: 30:AE:A4:26:45:4C
Subnet Mask: 255.255.255.0
Gateway IP: 192.168.168.138
DNS: 192.168.168.138
Thingspeak: Prepare Upload ( insert code here )
Start Uploading to ThingSpeak
Current URL String:
/update?api_key=XXXXXXXXXXXXXXXXXX&field1=0.00&field2=nan&field3=nan&field4=nan
# End of String #
Uploading to ThingSpeak
Connecting to host 'api.thingspeak.com' on port 80
Requesting url: GET /update?api_key=XXXXXXXXXXXXXXXXXX&field1=0.00&field2=nan&field3=nan&field4=nan HTTP/1.1
Host: api.thingspeak.com
Connection: close


Response: HTTP/1.1 200 OK

Try to use HTTP@80 for Thingspeak
Thingspeak will upload in 60000 Ticks( ms )
Thingspeak: Prepare Upload ( insert code here )
Start Uploading to ThingSpeak
Current URL String:
/update?api_key=XXXXXXXXXXXXXXXXXX&field1=0.00&field2=nan&field3=nan&field4=nan
# End of String #
Uploading to ThingSpeak
Connecting to host 'api.thingspeak.com' on port 80
Requesting url: GET /update?api_key=XXXXXXXXXXXXXXXXXX&field1=0.00&field2=nan&field3=nan&field4=nan HTTP/1.1
Host: api.thingspeak.com
Connection: close


Response: HTTP/1.1 200 OK

Try to use HTTP@80 for Thingspeak
Thingspeak will upload in 60000 Ticks( ms )

**Comment by lab-mathias-claussen** [comment]
Hi ginodecock,

it is scheduled for today to look into this isssue. It seems that there are some things going definitly wrong inside the Thingspeak modules. We will try to recreate this behaviour and fix it. As the internal sensors seems to work this is a bit strange in the first place. 

Best Regards

ElektorLabs

**Comment by lab-mathias-claussen** [comment]
Dear ginodecock, 
for the SDS011 we found the error in uart_pm_sensors.cpp , the value of result was not trasnfered back into the provided pointer, that is fixed in our local testbuild, for the TSL2561 this gonne be a bit more challaging as we run out of equipment with this kind of sensors currently. 

Regards

ElektorLabs

**Comment by ginodecock** [comment]
Ok thanks,

If you make the fix a available I'll test it. 

Grts, 
Gino

**Comment by lab-mathias-claussen** [comment]
Patch for the SDS011 has been submitted, for TSL2561 see #6

**Comment by ginodecock** [comment]
@lab-mathias-claussen After adding the patch the SDS011 values are send but they all have the value 0. This is not correct.

**Comment by lab-mathias-claussen** [comment]
Hi,

we have to inverstigate the issue with the device. 0 is definitly something that should not been returned. 

Regards 

ElektorLabs
