### ISSUE TITLE
NTP Client Lib

### ISSUE THREAD

**Issue by Pakl8** [ElektorLabs/191148-RemakeWeatherStation#7]
Using release 3.0.2 will result in a error when compiling and a constant reboot. 
Using release 3.0.1 will work fine.

Error: NTPClientLib.cpp:289:41: note: candidate 2: operator==(uint32_t {aka unsigned int}, uint32_t {aka unsigned int}) <built-in>
if (ntpServerIPAddress == (uint32_t)(0)) {

**Comment by lab-mathias-claussen** [comment]
Hi,

this is related to https://github.com/gmag11/NtpClient/issues/105 . For the time beeing currently we can recommend using the 3.01 for now till the bug is fixed.

Best Regards

**Comment by lab-mathias-claussen** [comment]
The project has changed from an ArduinoIDE Project to a PlattformIO project. This means that now NtpClient 3.0.1 is included, which shall "solve" the versioning problem for now.
