### ISSUE TITLE
MQTT Connector not transmitting data

### ISSUE THREAD

**Issue by calm4git** [ElektorLabs/191148-RemakeWeatherStation#8]
Does someone has the MQTT working? The MQTT will connect but not passing this line: if(Mapping != nullptr), line 207 in mqtt_task.cpp, so nothing is send. I have also the weather station mark 1, which works fine....

**Comment by lab-mathias-claussen** [comment]
Hi, 

the ussue has been addressed and if proven working, we can close this.

Best Regards

**Comment by Pakl8** [comment]
Thank you so much! I have got Rasp. PI with mosquitto running, filling in the MQTT Hostname, the MQTT connects repeatedly, when it's blank, it connects once, which is fine, as set in the enclosed snapshot.
![MQTT_Mrk2](https://user-images.githubusercontent.com/46988410/93388410-f2af0680-f86a-11ea-8684-d8aa72922a44.jpg)
 One other small remark: the webpage mentioned Upload Interval (minutes), but it's seconds.

**Comment by lab-mathias-claussen** [comment]
Hi,

thanks for the report. This afternoon a check for the new firmware is scheduled, so we can look into the issue.

Best Regards

Mathias Claußen

**Comment by lab-mathias-claussen** [comment]
MQTT has received fixes and shall now connect only once. Hostname shall not be blank for now and the intervall will use the minutes instead of using it as seconds.
