### ISSUE TITLE
Adafruit_TSL2591::begin() always returns true

### ISSUE THREAD

**Issue by Pakl8** [ElektorLabs/191148-RemakeWeatherStation#9]
Adafruit_TSL2591::begin() always returns true instead of returning real status from a function it calls. So the TSL2591 is added to the found sensors even if it's not connected. This problem is within the adafruit library and has allready been reported in https://github.com/adafruit/Adafruit_TSL2591_Library/issues/38, I took the easy way: just change line 126 in DeviceOnBus[TSL2591] = false; in i2c_sensors.cpp, so it's not in the list

**Comment by lab-mathias-claussen** [comment]
Hi PakI8,

we can see the issue and the broken place in the lib code. Also we can work arround it for the current version of the library but need to check if this breaks something else 

Best Regards

**Comment by lab-mathias-claussen** [comment]
PlattformIO project has been commited and Firmware is now at 1.5 solving the issue
